
// FAVORITES TYPES
export const FAVORITES_ADD_CITY = "FAVORITES_ADD_CITY";
export const FAVORITES_ADD_CITY_FAIL = "FAVORITES_ADD_CITY_FAIL";
export const FAVORITES_ADD_CITY_SUCCESS = "FAVORITES_ADD_CITY_SUCCESS";
export const FAVORITES_REMOVE_CITY_FAVORITES = "FAVORITES_REMOVE_CITY_FAVORITES";
export const FAVORITES_REMOVE_CITY_FAVORITES_FAIL = "FAVORITES_REMOVE_CITY_FAVORITES_FAIL";
export const FAVORITES_REMOVE_CITY_FAVORITES_SUCCESS = "FAVORITES_REMOVE_CITY_FAVORITES_SUCCESS";
export const FAVORITES_REFRESH_DATA = "FAVORITES_REFRESH_DATA";
export const FAVORITES_REFRESH_DATA_FAIL = "FAVORITES_REFRESH_DATA_FAIL";
export const FAVORITES_REFRESH_DATA_SUCCESS = "FAVORITES_REFRESH_DATA_SUCCESS";

// CITY WEATHER TYPES
export const CITY_WEATHER_GET_CITY_WEATHER = "CITY_WEATHER_GET_CITY_WEATHER";
export const CITY_WEATHER_GET_CITY_WEATHER_FAIL = "CITY_WEATHER_GET_CITY_WEATHER_FAIL";
export const CITY_WEATHER_GET_CITY_WEATHER_SUCCESS = "CITY_WEATHER_GET_CITY_WEATHER_SUCCESS";
export const CITY_WEATHER_GET_AUTO_COMPLETE = "CITY_WEATHER_GET_AUTO_COMPLETE";
export const CITY_WEATHER_GET_AUTO_COMPLETE_FAIL = "CITY_WEATHER_GET_AUTO_COMPLETE_FAIL";
export const CITY_WEATHER_GET_AUTO_COMPLETE_SUCCESS = "CITY_WEATHER_GET_AUTO_COMPLETE_SUCCESS";

// USER TYPES
export const USER_SET_TEMP_UNIT = "USER_SET_TEMP_UNIT";
export const USER_SET_THEME = "USER_SET_THEME";
